3000 #!/usr/bin/perl -w
3001 
3002 # Generate vectors.S, the trap/interrupt entry points.
3003 # There has to be one entry point per interrupt number
3004 # since otherwise there's no way for trap() to discover
3005 # the interrupt number.
3006 
3007 print "# generated by vectors.pl - do not edit\n";
3008 print "# handlers\n";
3009 print ".globl alltraps\n";
3010 for(my $i = 0; $i < 256; $i++){
3011     print ".globl vector$i\n";
3012     print "vector$i:\n";
3013     if(!($i == 8 || ($i >= 10 && $i <= 14) || $i == 17)){
3014         print "  pushl \$0\n";
3015     }
3016     print "  pushl \$$i\n";
3017     print "  jmp alltraps\n";
3018 }
3019 
3020 print "\n# vector table\n";
3021 print ".data\n";
3022 print ".globl vectors\n";
3023 print "vectors:\n";
3024 for(my $i = 0; $i < 256; $i++){
3025     print "  .long vector$i\n";
3026 }
3027 
3028 # sample output:
3029 #   # handlers
3030 #   .globl alltraps
3031 #   .globl vector0
3032 #   vector0:
3033 #     pushl $0
3034 #     pushl $0
3035 #     jmp alltraps
3036 #   ...
3037 #
3038 #   # vector table
3039 #   .data
3040 #   .globl vectors
3041 #   vectors:
3042 #     .long vector0
3043 #     .long vector1
3044 #     .long vector2
3045 #   ...
3046 
3047 
3048 
3049 
